export const AMOUNT_RAISERD_TEXT = "הסכום שגויס עד כה";
export const FORM_TARGET_TEXT = "מתוך יעד של";
export const SERVER_URL = "http://localhost:3000";
export const OVERVIEW_INTERVAL = 10000;
export const MAIN_COLOR = "#f4c911";
export const SUB_COLOR = "#012d45";
export const THIRD_COLOR = "#eaae20"
export const NUM_OF_GROUPS_TO_DISPLAY = 12;
export const ANIMATION_DELAT_BETWWEN_GROUP_ENTER = 200;